apiVersion: v1
kind: Service
metadata:
  name: piline-server-service
spec:
  type: NodePort
  selector:
    app: piline-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8686
      nodePort: 30080